export const privateEquityHeaders = [
  { label: 'Token', key: 'token' },
  { label: 'Symbol', key: 'symbol' },
  { label: 'Slug', key: 'slug' },
  { label: 'Price', key: 'price' },
  { label: 'Sequence No', key: 'sequenceNo' },
  { label: 'Open Sequence No', key: 'openSequenceNo' },
  { label: 'Open Active', key: 'openActive' },
  { label: 'Open Spotlight', key: 'openSpotlight' },
  { label: 'DP Quantity', key: 'availableQuantity' },
  { label: 'Active', key: 'active' },
  { label: 'Coming Soon', key: 'comingSoon' },
  { label: 'Only Few Left', key: 'onlyFewLeft' },
  { label: 'Sold Out', key: 'soldOut' },
  { label: 'Transferable', key: 'transferable' },
  { label: 'Sell', key: 'sell' },
  { label: 'Amalgamation', key: 'amalgamation' },
  { label: 'Block Deal', key: 'blockDeal' },
  { label: 'Capital Reduction', key: 'capitalReduction' },
  { label: 'Listed On Exchange', key: 'isListedOnExchange' },
  { label: 'CDSL', key: 'cdsl' },
  { label: 'NSDL', key: 'nsdl' },
  { label: 'Maximum Order Value', key: 'maxOrderValue' },
  { label: 'Max Quantity', key: 'maxQuantity' },
  { label: 'Minimum Order Value', key: 'minOrderValue' },
  { label: 'Minimum Quantity', key: 'minQuantity' },
  { label: 'Sector', key: 'sector' },
  { label: 'Head Quater', key: 'hq' },
  { label: 'Info', key: 'info' },
]

export const privateCreditHeaders = [
  { label: 'Gui Id', key: 'gui_id' },
  { label: 'Name', key: 'name' },
  { label: 'Price', key: 'price' },
  { label: 'Transaction fees', key: 'transaction_fees' },
  { label: 'Rate of returns', key: 'rate_of_returns' },
  { label: 'GST', key: 'gst' },
  { label: 'Active', key: 'active' },
  { label: 'Status', key: 'status' },
  { label: 'Sequence number', key: 'sequence_number' },
  { label: 'Subscribed value', key: 'subscribed_value' },
  { label: 'Max subscribed value', key: 'max_subscription_value' },
  { label: 'POL', key: 'pol' },
  { label: 'POD', key: 'pod' },
  { label: 'Start date', key: 'start_date' },
  { label: 'End date', key: 'end_date' },
  { label: 'Tentative start date', key: 'tentative_start_date' },
  { label: 'Tentative end date', key: 'tentative_end_date' },
  { label: 'Trade start date', key: 'trade_start_date' },
  { label: 'Trade end date', key: 'trade_end_date' },
  { label: 'Repaid date', key: 'repaid_date' },
  { label: 'Tenure', key: 'tenure' },
  { label: 'Tentative tenure', key: 'tentative_tenure' },
  { label: 'Available quantity', key: 'available_quantity' },
  { label: 'Min quantity', key: 'min_quantity' },
  { label: 'Max quantity', key: 'max_quantity' },
  { label: 'Min order value', key: 'min_order_value' },
  { label: 'Max order value', key: 'max_order_value' },
]

export const orderDetailsHeaders = [
  { label: 'Date', key: 'created_at' },
  { label: 'Account ID', key: 'gui_account_id' },
  { label: 'BOID', key: 'bo_id' },
  { label: 'ISIN', key: 'isin' },
  { label: 'Company Name', key: 'symbol' },
  { label: 'Order ID', key: 'gui_order_id' },
  { label: 'First Name', key: 'first_name' },
  { label: 'Last Name', key: 'last_name' },
  { label: 'Quantity', key: 'quantity' },
  { label: 'Price', key: 'price' },
  { label: 'Order Value', key: 'order_value' },
  { label: 'Transaction Fees', key: 'transaction_fee' },
  { label: 'Stampduty', key: 'stamp_duty' },
  { label: 'GST', key: 'gst' },
  { label: 'Documentation Charges', key: 'documentation_charges' },
  { label: 'Total Transaction Value', key: 'transaction_value' },
  { label: 'Bank Name', key: 'bank_name' },
  { label: 'Bank Account Number', key: 'account_number' },
  { label: 'Transaction ID', key: 'gui_transaction_id' },
  { label: 'Order Status', key: 'status' },
  { label: 'order_id', key: 'order_id' },
  { label: 'email', key: 'email' },
  { label: 'Mobile', key: 'mobile' },
]

export const panPendingUserExportKeyLabels = [
  { label: 'account_id', key: 'account_id' },
  { label: 'gui_account_id', key: 'gui_account_id' },
  { label: 'email', key: 'email' },
  { label: 'mobile', key: 'mobile' },
  { label: 'first_name', key: 'first_name' },
  { label: 'middle_name', key: 'middle_name' },
  { label: 'last_name', key: 'last_name' },
  { label: 'status', key: 'status' },
  { label: 'onboarding_tracker', key: 'onboarding_tracker' },
  { label: 'boid', key: 'bo_id' },
  { label: 'pan', key: 'pan' },
  { label: 'portal_linked', key: 'portal_linked' },
  { label: 'dob', key: 'dob' },
  { label: 'orders_count', key: 'orders_count' },
  { label: 'whatsapp_notification', key: 'whatsapp_notification' },
  { label: 'active', key: 'active' },
  { label: 'account_balance', key: 'account_balance' },
  { label: 'withdraw_balance', key: 'withdraw_balance' },
  { label: 'evaluation_expiry_date', key: 'evaluation_expiry_date' },
  { label: 'pan_updated_at', key: 'pan_updated_at' },
  { label: 'created_at', key: 'created_at' },
  { label: 'updated_at', key: 'updated_at' },
]
export const exportPcHoldingsHeaders = [
  { label: 'Account ID', key: 'gui_account_id' },
  { label: 'First Name', key: 'first_name' },
  { label: 'Middle Name', key: 'middle_name' },
  { label: 'Last Name', key: 'last_name' },
  { label: 'Symbol', key: 'symbol' },
  { label: 'Mobile', key: 'mobile' },
  { label: 'Email', key: 'email' },
  { label: 'Charges', key: 'charges' },
  { label: 'Price', key: 'price' },
  { label: 'Quantity', key: 'quantity' },
  { label: 'Returns', key: 'returns' },
  { label: 'Status', key: 'status' },
  { label: 'Subscription Amount', key: 'subscription_amount' },
  { label: 'Min Repayment Amount', key: 'min_repayment_amount' },
  { label: 'Created At', key: 'created_at' },
]

export const exportPcHoldingsEndedHeaders = [
  { label: 'holding_id', key: 'id' },
  { label: 'Account ID', key: 'gui_account_id' },
  { label: 'First Name', key: 'first_name' },
  { label: 'Middle Name', key: 'middle_name' },
  { label: 'Last Name', key: 'last_name' },
  { label: 'Symbol', key: 'symbol' },
  { label: 'Mobile', key: 'mobile' },
  { label: 'Email', key: 'email' },
  { label: 'Charges', key: 'charges' },
  { label: 'Price', key: 'price' },
  { label: 'Quantity', key: 'quantity' },
  { label: 'Returns', key: 'returns' },
  { label: 'Status', key: 'status' },
  { label: 'Subscription Amount', key: 'subscription_amount' },
  { label: 'Min Repayment Amount', key: 'min_repayment_amount' },
  { label: 'Created At', key: 'created_at' },
]
export const acquisitionHeaders = [
  { label: 'Email', key: 'email' },
  { label: 'Status', key: 'status' },
  { label: 'Access Code', key: 'code' },
  { label: 'Sent Code', key: 'sentCode' },
  { label: 'Registered', key: 'registered' },
  { label: 'Created At', key: 'createdAt' },
  { label: 'Updated At', key: 'updatedAt' },
]
export const orderAnalyticsAccountsHeaders = [
  { label: 'GUI Account ID', key: 'gui_account_id' },
  { label: 'First Name', key: 'firstName' },
  { label: 'Last Name', key: 'lastName' },
  { label: 'Email', key: 'email' },
  { label: 'Mobile', key: 'mobile' },
  { label: 'Status', key: 'status' },
  { label: 'Orders Count', key: 'orders_count' },
  {
    label: 'WhatsApp Notification',
    key: 'whatsapp_notification',
  },
  { label: 'Created At', key: 'created_at' },
  {
    label: 'Evaluation Expiry Date',
    key: 'evaluationExpiryDate',
  },
  { label: 'Onboarding Tracker', key: 'onBoardingTracker' },
  { label: 'Active', key: 'active' },
]
export const orderAnalyticsOrdersHeaders = [
  { label: 'Order ID', key: 'gui_order_id' },
  { label: 'Account ID', key: 'gui_account_id' },
  { label: 'First Name', key: 'firstName' },
  { label: 'Last Name', key: 'lastName' },
  { label: 'Email', key: 'email' },
  { label: 'Mobile', key: 'mobile' },
  { label: 'Symbol', key: 'symbol' },
  { label: 'Price', key: 'price' },
  { label: 'Quantity', key: 'quantity' },
  { label: 'Status', key: 'status' },
  { label: 'Created At', key: 'created_at' },
]

export const peHoldingHeaders = [
  { label: 'Account ID', key: 'account_id' },
  { label: 'GUI Account ID', key: 'gui_account_id' },
  { label: 'First Name', key: 'first_name' },
  { label: 'Middle Name', key: 'middle_name' },
  { label: 'Last Name', key: 'last_name' },
  { label: 'Symbol', key: 'symbol' },
  { label: 'Token', key: 'token' },
  { label: 'Mobile', key: 'mobile' },
  { label: 'Email', key: 'email' },
  { label: 'Price', key: 'price' },
  { label: 'Quantity', key: 'quantity' },
  { label: 'Holding ID', key: 'holding_id' },
  { label: 'Buy Transaction Fees', key: 'buy_transaction_fees' },
  { label: 'Sell Transaction Fees', key: 'sell_transaction_fees' },
  { label: 'Amount', key: 'amount' },
  { label: 'Created At', key: 'created_at' },
]

export const pcHoldingHeaders = [
  { label: 'Holding ID', key: 'id' },
  { label: 'Account ID', key: 'account_id' },
  { label: 'GUI Account ID', key: 'gui_account_id' },
  { label: 'First Name', key: 'first_name' },
  { label: 'Middle Name', key: 'middle_name' },
  { label: 'Last Name', key: 'last_name' },
  { label: 'Symbol', key: 'symbol' },
  { label: 'Mobile', key: 'mobile' },
  { label: 'Email', key: 'email' },
  { label: 'Charges', key: 'charges' },
  { label: 'Buy Transaction Fees', key: 'buy_transaction_fees' },
  { label: 'Price', key: 'price' },
  { label: 'Quantity', key: 'quantity' },
  { label: 'Returns', key: 'returns' },
  { label: 'Status', key: 'status' },
  { label: 'Subscription Amount', key: 'subscription_amount' },
  { label: 'Min Repayment Amount', key: 'min_repayment_amount' },
  { label: 'Created At', key: 'created_at' },
]

export const wishlistHeaders = [
  { label: 'wishlist_id', key: 'wishlist_id' },
  { label: 'Token', key: 'token' },
  { label: 'Name', key: 'name' },
  { label: 'Account Id', key: 'gui_account_id' },
  { label: 'First Name', key: 'first_name' },
  { label: 'Middle Name', key: 'middle_name' },
  { label: 'Last Name', key: 'last_name' },
  { label: 'Email', key: 'email' },
  { label: 'Mobile', key: 'mobile' },
  { label: 'Notified', key: 'notified' },
]

export const pcWishlistHeaders = [
  { label: 'Token', key: 'name' },
  { label: 'Account Id', key: 'gui_account_id' },
  { label: 'First Name', key: 'first_name' },
  { label: 'Last Name', key: 'last_name' },
  { label: 'Email', key: 'email' },
  { label: 'Mobile', key: 'mobile' },
  { label: 'Notified', key: 'notify' },
]
export const nominatorHeaders = [
  { label: 'Name', key: 'name' },
  { label: 'Code', key: 'code' },
  { label: 'Logo', key: 'logo' },
  { label: 'Accounts', key: 'accounts' },
  { label: 'Created At', key: 'created_at' },
]

export const nominatorAccountsHeaders = [
  { label: 'Account ID', key: 'gui_account_id' },
  { label: 'First Name', key: 'first_name' },
  { label: 'Last Name', key: 'last_name' },
  { label: 'Mobile', key: 'mobile' },
  { label: 'Email', key: 'email' },
  { label: 'Orders', key: 'orders_count' },
  { label: 'Order value', key: 'order_value' },
  { label: 'Transaction fee', key: 'transaction_fee' },
  { label: 'Stamp Duty', key: 'stamp_duty' },
  { label: 'Holdings Count', key: 'holdings_count' },
  { label: 'Holding Value', key: 'holding_value' },
  { label: 'Status', key: 'status' },
  { label: 'Created At', key: 'created_at' },
]

export const pcEnquiryHeaders = [
  { label: 'account_id', key: 'user_id' },
  { label: 'Account ID', key: 'gui_account_id' },
  { label: 'First Name', key: 'first_name' },
  { label: 'Last name', key: 'last_name' },
  { label: 'Email', key: 'email' },
  { label: 'Mobile', key: 'mobile' },
  { label: 'Wallet Balance', key: 'wallet_balance' },
  { label: 'No of Holdings', key: 'no_of_holdings' },
  { label: 'No of Paid Orders', key: 'no_of_paid_orders' },
  { label: 'Total Holdings Amount', key: 'total_holdings_amount' },
  { label: 'PC Active', key: 'pc_active' },
  { label: 'Created At', key: 'created_at' },
]
